import os

DISCORD_TOKEN = os.getenv('DISCORD_TOKEN')
D2K_SERVER_ID = int(os.getenv('D2K_SERVER_ID'))
PLAYER_ONLINE_CHANNEL_ID = int(os.getenv('PLAYER_ONLINE_CHANNEL_ID'))
SEND_MESSAGE_CHANNEL_ID = int(os.getenv("SEND_MESSAGE_CHANNEL_ID"))
CNCNET_CHANNEL_KEY = os.getenv('CNCNET_CHANNEL_KEY')
APP_CREATOR_ID = int(os.getenv('APP_CREATOR_ID'))
