import os

DISCORD_TOKEN = os.getenv('DISCORD_TOKEN')
D2K_SERVER_ID = int(os.getenv('D2K_SERVER_ID'))
TIME_CHANNEL_ID = int(os.getenv('TIME_CHANNEL_ID'))
PLAYER_ONLINE_CHANNEL_ID = int(os.getenv('PLAYER_ONLINE_CHANNEL_ID'))
CNCNET_CHANNEL_KEY = os.getenv('CNCNET_CHANNEL_KEY')
